version: '3.8'

services:
  mention-bot:
    image: ghcr.io/dkiejcnosoajrfpjwnr-star/mention-all-bot:master
    container_name: mention-all-bot
    environment:
      TGBOT_TOKEN: ${TGBOT_TOKEN}
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./database.db:/app/database.db
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
